FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        pkg-config \
        ffmpeg \
        libavcodec-dev \
        libavformat-dev \
        libavutil-dev \
        libswscale-dev \
        libswresample-dev \
        libasound2-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
